os: Visual Studio 2015

environment:
  nodejs_version: '8.11'
  matrix:
  - node_installer: npm

cache:
  - .eslintcache
  - node_modules
  - '%USERPROFILE%\.electron'

branches:
  only:
    - master
    - /^v[0-9].[0-9].[0-9].*/

version: '{build}'

install:
  - cmd: regedit /s script\default-to-tls12-on-appveyor.reg
  - git submodule update --init --recursive
  - npm install --prune

test_script:
  - npm run test

for:
-
  branches:
    only:
      - /^v[0-9].[0-9].[0-9].*/

  before_build:
    - ps: script\setup-windows-certificate.ps1

  build_script:
    - npm run make

  after_build:
    - ps: script\cleanup-windows-certificate.ps1

  artifacts:
    # pushing all *.nupkg files in build directory recursively
    - path: out\make\**\*.nupkg
      name: deploy-nupkg
    - path: out\make\**\*.exe
      name: deploy-exe
    - path: out\make\**\RELEASES
      name: deploy-RELEASES

  deploy:
    description: ''
    provider: GitHub
    auth_token:
      secure: Qw9G7NiqHJZHtZ8tQTYzzEqYaLzDEkg4SV2rWKOac4gtNL4UBNGKCvjKQCOq7kM1 # your encrypted token from GitHub
    artifact: /^deploy-.*/
    draft: true
    on:
      branch: /^v[0-9].[0-9].[0-9].*/  # release from tags only
      appveyor_repo_tag: true          # deploy on tag push only
