notifications:
  email: false

dist: trusty

sudo: false

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

language: node_js
node_js:
  - "8.11.3"

cache:
  directories:
    - node_modules

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master
    - /^v[0-9].[0-9].[0-9].*/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - gnome-keyring
      - libsecret-1-dev
      - python-gnomekeyring
      - fakeroot
      - rpm
      - zip

install:
  - npm install --prune

jobs:
  include:
  - stage: test
    name: "Unit Tests"
    script: "./script/test"
  - stage: predeploy
    name: "Setup Mac Keychain"
    if: os = mac AND fork = false
    script: "./script/setup-macos-keychain"
  - stage: deploy
    name: "Build"
    script: "npm run make"
    if: tag = ^v[0-9].[0-9].[0-9].*$
  - name: "Deploy to GitHub Releases"
    script: skip
    deploy:
      skip_cleanup: true
      provider: releases
      name: ${TRAVIS_TAG}
      tag_name: ${TRAVIS_TAG}
      draft: true
      file_glob: true
      api_key:
        secure: ${GITHUB_TOKEN}
      file:
        - "out/make/**/*.zip"
        - "out/make/**/*.rpm"
        - "out/make/**/*.deb"
