notifications:
  email: false

dist: trusty

sudo: false

language: node_js
node_js:
  - "8.11.3"

cache:
  directories:
    - node_modules

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master
    - /^v[0-9].[0-9].[0-9].*/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - gnome-keyring
      - libsecret-1-dev
      - python-gnomekeyring
      - fakeroot
      - rpm
      - zip

install:
  - npm install --prune

os:
  - osx
  - linux

stages:
  - name: setup
    if: os = mac
  - test
  - name: deploy
    if: tag =~ /^v[0-9].[0-9].[0-9].*$/

jobs:
  include:
    - stage: setup
      script: ./script/setup-macos-keychain
    - stage: test
      script: ./script/test
    - stage: deploy
      script: npm run make
      deploy:
        skip_cleanup: true
        provider: releases
        name: ${TRAVIS_TAG}
        tag_name: ${TRAVIS_TAG}
        draft: true
        file_glob: true
        api_key:
          secure: ${GITHUB_TOKEN}
        file:
          - "out/make/**/*.zip"
          - "out/make/**/*.rpm"
          - "out/make/**/*.deb"
