notifications:
  email: false

dist: trusty

sudo: false

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

language: node_js
node_js:
  - "8.11.3"

cache:
  directories:
    - node_modules

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master
    - /^v[0-9].[0-9].?[0-9]?-?.*/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - gnome-keyring
      - libsecret-1-dev
      - python-gnomekeyring
      - fakeroot
      - rpm

install:
  - npm install --prune

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start); fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi

script:
  - ./script/test
  - npm run make

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: ${GITHUB_TOKEN}
  file_glob: true
  file:
    - "./out/make/*.zip"
    - "./out/make/*.rpm"
    - "./out/make/*.deb"
  on:
    all_branches: true
    tags: true
